[workspace]
members = [
  "prover",
  "service",
  #"executor",
  "prover-scheduler",
  "metrics",
  "prover-core",
  "guests/guest-revm",
  "guests/aggregation",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
