[workspace]
members = [
  "prover",
  "service",
  #"executor",
  "prover-scheduler",
  "metrics",
  "prover-core",
  "guests/revm",
  "guests/aggregation",
]

[workspace.package]
version = "0.2.0"
edition = "2021"

workspace.resolver = "2"