[workspace]
members = [
  "prover",
  "service",
  "executor",
  "prover-scheduler",
  "metrics",
  "prover-core",
  "guests/revm",
  "guests/aggregation",
]

[workspace.package]
version = "0.1.1"
edition = "2021"

resolver = "2"
