version: '3'

services:
  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: state
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: service.Dockerfile
    environment:
      DATABASE_URL: postgresql://root:password@database:5432/state
    depends_on:
      - database
    ports:
      - "50000:50000"
