[package]
name = "service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.8.1"
prost = "0.11.0"
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-stream = { version = "0.1" }

# biz
statedb = { path = "../statedb" }
prover = { path = "../prover" }
plonky = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main" }
starky = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main" }
algebraic = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main" }
utils =  { path = "../utils" }

lazy_static = "1.4.0"

# config
serde = "1.0.92"
serde_derive = "1.0.92"
toml = "0.5.1"
uuid = { version = "1.2", features = ["v4", "fast-rng", "macro-diagnostics"] }

#log
log = "0.4.0"
env_logger = "0.10"

[build-dependencies]
tonic-build = "0.8.0"
