[package]
name = "prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
dsl_compile.workspace = true
groth16.workspace = true
log.workspace = true
powdr-number.workspace = true
recursion.workspace = true
serde_json.workspace = true
serde.workspace = true
starky.workspace = true
uuid.workspace = true
zkvm.workspace = true

[dev-dependencies]
env_logger.workspace = true
