[package]
name = "prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starky = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main", package="plonky"}
plonky = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main" , package="plonky"}
dsl_compile = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main" , package="plonky"}

tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1" }
