[package]
name = "prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starky = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main", package="starky"}
plonky = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main" , package="plonky"}
groth16 = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main" , package="groth16"}
algebraic = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main" , package="algebraic"}
dsl_compile = { git = "https://github.com/0xEigenLabs/eigen-zkvm", branch = "main" }

tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1" }
uuid = { version = "1.2", features = ["v4", "fast-rng", "macro-diagnostics"] }

serde = { version = "1.0", features = ["derive"] }

# serde_json is just for the example, not required in general
serde_json = "1.0"

log = "0.4.0"

[dev-dependencies]
env_logger = "0.10"
