[package]
name = "prover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starky = { git = "https://github.com/captainlee1024/eigen-zkvm", branch = "fix-powdr-binary-mux2", default-features = false }
recursion = { git = "https://github.com/captainlee1024/eigen-zkvm", branch = "fix-powdr-binary-mux2", default-features = false }
plonky = { git = "https://github.com/captainlee1024/eigen-zkvm", branch = "fix-powdr-binary-mux2", default-features = false }
groth16 = { git = "https://github.com/captainlee1024/eigen-zkvm", branch = "fix-powdr-binary-mux2", default-features = false  }
algebraic = { git = "https://github.com/captainlee1024/eigen-zkvm", branch = "fix-powdr-binary-mux2"  }
dsl_compile = { git = "https://github.com/captainlee1024/eigen-zkvm", branch = "fix-powdr-binary-mux2" }
zkvm = { git = "https://github.com/captainlee1024/eigen-zkvm", branch = "fix-powdr-binary-mux2", default-features = false }

powdr = { git = "https://github.com/0xEigenLabs/powdr", branch = "binary-mux2", default-features = false }

tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread", "signal", "sync"] }
uuid = { version = "1.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
log = "0.4.0"

[dev-dependencies]
env_logger = "0.10"

[features]
default = []
avx512 = ["starky/avx512", "recursion/avx512", "plonky/avx512", "zkvm/avx512", "powdr/starky-avx512"]
